### ISSUE TITLE
Nice work but still some problems and questions

### ISSUE THREAD

**Issue by ghost** [anshkumar/yolact#1]
Hey anshkuma, 

First of all. Nice work! But I have still some questions. 

1. Do I have to clone this repo https://github.com/tensorflow/models ? 
Looks like you used the protos and the box_list.py in utils? 
Right now I copied those and adjusted the box_list because it had some further dependencies.

2. Further I had to change line 32 in dataset_coco.py to "files = tf.io.matching_files(os.path.join(tfrecord_dir, "coco_%s.*" % subset))"

3. And in the tfrecord_decoder.py it should be             'gt_classes': parsed_tensors['image/object/class/label_id'] right? Otherwise a string is interpreted as int64 which makes problems.

With these adjustments, the training is running. Hopefully with good results.

Let me know if I made any mistakes.

**Comment by anshkumar** [comment]
You don't have to clone any repository. I've tried fixing the dependencies  form tensorflow repo but still if you are finding errors, you can paste it here, will fix it.

Currently, records file should have name as "train.record" and "val.record", will add path to individual file in future.

I've used the same nomenclature as used in tensorflow-object-detection api for creating tfrecord files, as mentioned h[ere](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/using_your_own_dataset.md), which is as follows:

```
  tf_example = tf.train.Example(features=tf.train.Features(feature={
      'image/height': dataset_util.int64_feature(height),
      'image/width': dataset_util.int64_feature(width),
      'image/filename': dataset_util.bytes_feature(filename),
      'image/source_id': dataset_util.bytes_feature(filename),
      'image/encoded': dataset_util.bytes_feature(encoded_image_data),
      'image/format': dataset_util.bytes_feature(image_format),
      'image/object/bbox/xmin': dataset_util.float_list_feature(xmins),
      'image/object/bbox/xmax': dataset_util.float_list_feature(xmaxs),
      'image/object/bbox/ymin': dataset_util.float_list_feature(ymins),
      'image/object/bbox/ymax': dataset_util.float_list_feature(ymaxs),
      'image/object/class/text': dataset_util.bytes_list_feature(classes_text),
      'image/object/class/label': dataset_util.int64_list_feature(classes),
      'image/object/mask': dataset_util.bytes_list_feature(encoded_mask_png)
  }))
```
`classes` is classs id (an integer value) given to the class, starting from 1.

**Comment by ghost** [comment]
As I mentioned .. the protos folder and the box_list.py are not included in your repo. You should add them.

Yes I manged to get a working tfrecord file. But its a bit confusing, cause the original tensorflow yolact repo, yours and the object_detection tensorflow repo all diverged regarding the tf_example definition.

**Comment by ghost** [comment]
During training I get this error after a few hundred iterations: Do you know whats going wrong here? The dataset is the original coco set.

```
Traceback (most recent call last):
  File "train.py", line 402, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "train.py", line 246, in main
    for image, labels in train_dataset:
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 736, in __next__
    return self.next()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 772, in next
    return self._next_internal()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/iterator_ops.py", line 764, in _next_internal
    return structure.from_compatible_tensor_list(self._element_spec, ret)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/context.py", line 2105, in execution_mode
    executor_new.wait()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/executor.py", line 67, in wait
    pywrap_tfe.TFE_ExecutorWaitForAllPendingNodes(self._handle)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes at component 0: expected [?,550,550,3] but got [1,550,550,1].
```

**Comment by anshkumar** [comment]
I've added "box_list.py" in "utils", you can try now. It should work without further dependencies.

Check if any grayscale image is not being inserted in the record as the error message is saying that the dimension of the image it got is [1,550,550,1]. So, instead of RGB it's getting only single channel.

Also check if Masks inside the record file don't have extra dimensions. I encode mask in record as follows:
```
def createMask(img, pts):
    mask = np.zeros(img.shape[:2], np.uint8)
    cv2.drawContours(mask, [pts], -1, (255, 255, 255), -1, cv2.LINE_AA)
    return mask

mask = createMask(_img, pts)
encoded_png = cv2.imencode('.png', mask)[1].tostring()
encoded_mask_png.append(encoded_png)
```

**Comment by ghost** [comment]
Thanks a lot. I will check. But maybe you can provide your script for creating the tfrecord from the coco data? I used the create_coco_tfrecord.py in your repo, but seems like you used another one.

**Comment by anshkumar** [comment]
I've trained it on custom dataset, so don't have another tfrecord script. But you can add the following line [here](https://github.com/anshkumar/yolact/blob/315325dd04b1baa97cc6a6406041275c70626c86/data/yolact_parser.py#L67)
```
if tf.shape(image)[-1] == 1:
       image = tf.image.grayscale_to_rgb(image)
```
This will convert any single channel image to 3 channels.

**Comment by anshkumar** [comment]
Grayscale image support added.
