### ISSUE TITLE
Amazing ! I have some questions about tflite :o 

### ISSUE THREAD

**Issue by emilio-desousa** [anshkumar/yolact#2]
Hey anshkuma,

First of all, thank you for your work ! 

I have a question about `to_tflite.py`:

-   Do you have examples of inference times on tflite and for which hardware? 
I have a big time constraint for my project and your implementation could save my life!

Thank you for all !

**Comment by anshkumar** [comment]
I don't have hardware specific benchmarking.

**Comment by emilio-desousa** [comment]
Okay thanks, and sorry but does tflite.py work? On which device did you use it pls? 

Thanks!

**Comment by anshkumar** [comment]
I've tested it using tf >= 2.4 on servers only. It's working without INT8 quantization.

**Comment by emilio-desousa** [comment]
Okay, thanks for the answers 👍
