### ISSUE TITLE
Please port yolact-edge to tTF lite and TPU hardware!! If it is possible XD 

### ISSUE THREAD

**Issue by FPSychotic** [anshkumar/yolact#3]
Apart of the above, thanks by make this possible.
Yolact Edge is x3 faster than Yolact,, I get 9fps on Jetson Xavier NX with TRT conversion at 512x512 in realtime videocamera stream,  in 240x240 with TPU I guess (without any base XD) maybe could get 1 or 2fps which would be great.

Cheers!

**Comment by anshkumar** [comment]
Currently, I'm testing YOLACT++. After that will move on to Yolact Edge.

**Comment by FPSychotic** [comment]
If I can help you to test anything just let me know, I have a  a Jetson Nano and NX that don't receive a good use, as I have not enough knowledge. 
Yolact Edge is working me at 10fps
